---
title: "Week 1 Report"
author: "Giles Carlos, Alyssandrei Parinas, Cadence Pinkerton, James Owens, Mia Chiu "
date: '2022-06-28'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)

```

# Loading in Data

```{r message=FALSE}
ab <- readr::read_csv(here::here("data/std_beta_ab_iti_ab.csv"), col_names = FALSE)
bc <- readr::read_csv(here::here("data/std_beta_bc_iti_ab.csv"), col_names = FALSE)
cd <- readr::read_csv(here::here("data/std_beta_cd_iti_ab.csv"), col_names = FALSE)
de <- readr::read_csv(here::here("data/std_beta_de_iti_ab.csv"), col_names = FALSE)
```


# Plot AB

```{r}
ab_means <- 
  ab %>% 
  mutate(mean_beta_ab = rowMeans(ab)) %>% 
  ungroup() %>% 
  mutate(time = row_number()) %>% 
  select(time, mean_beta_ab)

ab_plot <- 
  ggplot(ab_means, aes(x = time, y = mean_beta_ab)) +
  geom_line() + 
  labs(x = "Time",
       y = "Mean of Beta AB Coefficient") 
```

# Plot BC

```{r}
bc_means <-
  bc %>% 
  mutate(mean_beta_bc = rowMeans(bc)) %>% 
  ungroup() %>% 
  mutate(time = row_number()) %>% 
  select(time, mean_beta_bc)

bc_means %>% 
  ggplot(aes(x = time, y = mean_beta_bc)) +
  geom_line(color = "#009E73") +
  labs(x = "Time",
       y = "Mean of Beta BC Coefficient")

bc_plot <- geom_line(data = bc_means, aes(y = mean_beta_bc), colour = "#009E73")
```



# Plot CD
```{r}
cd_means <- 
  cd %>% 
  mutate(mean_beta_cd = rowMeans(cd)) %>% 
  ungroup() %>% 
  mutate(time = row_number()) %>% 
  select(time, mean_beta_cd)

cd_means %>% 
  ggplot(aes(x = time, y = mean_beta_cd)) +
  geom_line(color = 'darkblue') + 
  labs(x = "Time",
       y = "Mean of Beta CD Coefficient") 

cd_line <- geom_line(data = cd_means, aes(y = mean_beta_cd), colour = 'darkblue')

```

# Plot DE

```{r}
de_means <- 
  de %>% 
  mutate(mean_beta_de = rowMeans(de)) %>% 
  ungroup() %>% 
  mutate(time = row_number()) %>% 
  select(time, mean_beta_de)

de_means %>% 
  ggplot(aes(x = time, y = mean_beta_de)) +
  geom_line(colour = "#56B4E9") + 
  labs(x = "Time",
       y = "Mean of Beta DE Coefficient") 

de_line <- geom_line(data = de_means, aes(y = mean_beta_de), colour = "#56B4E9")
```

# Combined Plot

```{r}
(ab_plot +
  bc_plot +
  cd_line +
  de_line) +
  labs(x = "Time",
       y = "Mean of Beta AB, BC, CD, DE Coefficient")
```

